version: '3.8'

services:
  lumeor-web:
    image: nginx:alpine
    container_name: lumeor-tienda
    ports:
      - "8085:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - lumeor-network

networks:
  lumeor-network:
    driver: bridge
